### ISSUE TITLE
Derive Macro error

### ISSUE THREAD

**Issue by Gvstavo** [rusterlium/rustler#348]
Following the basic example in the docs:

**Comment by Gvstavo** [comment]
Following the basic example in the docs:

#[derive(NifMap)]
struct AddMap {
    lhs: i32,
    rhs: i32,
} 

I'm getting this error 

error[E0107]: wrong number of type arguments: expected 1, found 2
   --> src/lib.rs:573:34
    |
573 | #[derive(Clone, Debug, Eq, Hash, NifMap)]
    |                                  ^^^^^^ unexpected type argument


Rustler version : 0.21.1"
Rust version: 1.40

**Comment by evnu** [comment]
Thanks for your report!

We just released v0.22.0. With that, we also test the templates with CI (which was not done with v0.21.0, IIRC). I just ran the template test manually and it worked, so I believe this issue here can be closed. Please reopen if this problem can still be reproduced with v0.22.0 or above.
